[package]
name = "rust7days_02_useful_traits"
version = "0.1.0"
authors = ["Jeffrey Knight <jeffrey.knight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
